name: json_class
description: An abstract class to assist with converting to and from JSON with various primitive parsers.
version: 1.0.7+2
homepage: https://github.com/peiffer-innovations/json_class

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  logging: ^0.11.4
  meta: ^1.2.4

dev_dependencies:
  test: any
  test_coverage: any
