name: jsonable
description: An abstract class to assist with converting to and from JSON with various primitive parsers.
version: 1.0.0
homepage: https://github.com/peiffer-innovations/jsonable

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  logging: ^0.11.4

dev_dependencies:
  test: any
  test_coverage: any

