name: json_class
description: An abstract class to assist with converting to and from JSON with various primitive parsers.
version: 2.1.2+4
homepage: https://github.com/peiffer-innovations/json_class

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  logging: ^1.0.2
  meta: ^1.7.0

dev_dependencies:
  test: ^1.20.1
