name: 'json_class'
description: 'An abstract class to assist with converting to and from JSON with various primitive parsers.'
version: '2.1.2+7'
homepage: 'https://github.com/peiffer-innovations/json_class'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  intl: '^0.17.0'
  logging: '^1.0.2'
  meta: '^1.7.0'

dev_dependencies: 
  test: '^1.21.3'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
