name: 'json_class'
description: 'An abstract class to assist with converting to and from JSON with various primitive parsers.'
version: '2.2.0'
homepage: 'https://github.com/peiffer-innovations/json_class'

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  intl: '^0.18.0'
  logging: '^1.1.1'
  meta: '^1.8.0'

dev_dependencies:
  flutter_lints: '^2.0.1'
  test: '^1.23.1'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
